The imaginary part of the retarded polarization shoulb be negative definite (or the retarded response function should be, see page 414 in the book by Stefanucci and van Leeuwen). 

In [12]:
import numpy as np

PATH = "/usr/scratch/bucaramanga/awinka/quatrex_results/testing/diag_polarization/"
diag_el_1 = "_g2p_601x601_iter0.npy"
pg_1 = np.load(PATH+"pg"+diag_el)
pl_1 = np.load(PATH+"pl"+diag_el)
pr_1 = np.load(PATH+"pr"+diag_el)
diag_el_2 = "_g2p_201x201_iter0.npy"
pg_2 = np.load(PATH+"pg"+diag_el)
pl_2 = np.load(PATH+"pl"+diag_el)
pr_2 = np.load(PATH+"pr"+diag_el)

In [17]:
num_orbs = 792
num_energy = 512
pg_diag = np.zeros((num_orbs, num_energy), dtype=np.complex128)
pl_diag = np.zeros((num_orbs, num_energy), dtype=np.complex128)
pr_diag = np.zeros((num_orbs, num_energy), dtype=np.complex128)
for i in range(num_orbs):
    diag_el = "_g2p_"+str(i)+"x"+str(i)+"_iter0.npy"
    pg_diag[i] = np.load(PATH+"pg"+diag_el)
    pl_diag[i] = np.load(PATH+"pl"+diag_el)
    pr_diag[i] = np.load(PATH+"pr"+diag_el)

In [23]:
bad_inds = np.where(np.imag(pg_diag[1]) > 0)
print(bad_inds)

(array([319, 321, 324, 325, 326, 327, 328, 329, 330, 332, 333, 335, 336,
       338, 339, 340, 341, 342, 344, 345, 347, 348, 351, 354, 357, 359,
       360, 362, 363, 366, 372, 374, 375, 378, 387, 390, 393, 394, 395,
       396, 397, 398, 399, 402, 404, 405, 406, 407, 408, 409, 410, 411,
       413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
       426, 427, 428, 429, 430, 431, 432, 434, 435, 438, 439, 440, 441,
       443, 444, 445, 446, 453, 456, 457, 459, 461, 462, 471, 472, 474,
       476, 477, 478, 479, 480, 482, 483, 484, 485, 486, 488, 489, 490,
       492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504,
       505, 506, 507, 509, 510, 511]),)


In [43]:
bad_inds = np.where(np.imag(pr_diag[5]) > 0)
print(bad_inds)
print(bad_inds[0].shape)

(array([  1,   2,   4,   6,   7,   8,   9, 309, 310, 311, 312, 313, 314,
       315, 317, 319, 320, 321, 322, 323, 326, 327, 328, 330, 332, 333,
       334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 346, 347,
       348, 349, 350, 352, 353, 354, 355, 356, 359, 363, 366, 379, 383,
       385, 387, 389, 392, 395, 401, 402, 405, 407, 408, 420, 422, 423,
       425, 427, 428, 429, 430, 431, 432, 434, 435, 437, 439, 440, 442,
       448, 449, 450, 451, 453, 456, 457, 458, 460, 462, 463, 465, 466,
       467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 480, 481,
       482, 483, 484, 490, 491, 493, 496, 501, 502, 505, 507, 508, 510]),)
(117,)


In [68]:
# print(np.imag(pr_diag[5][bad_inds]))
it = 400
print(np.imag(pg_diag-pl_diag).max())
print(np.imag(pr_diag).max())


1.877731650880216e-16
6.458367768617744e-16


array([ 1.87878192e-17-2.05145179e-07j,  1.66742389e-17-1.92758302e-07j,
        1.24399086e-17-1.95055425e-07j,  1.48325418e-17-4.43445405e-08j,
        1.77498629e-17-3.12706591e-07j,  1.59307013e-17-2.89551782e-07j,
        3.06145603e-18-2.35007577e-07j,  8.33406285e-18-1.91740448e-07j,
        1.55294204e-17-1.44453818e-07j, -6.69671185e-18-1.07656550e-07j,
        1.31202365e-17-1.42278488e-07j, -9.33469654e-19-5.57647262e-09j,
        5.51076512e-18-7.66020574e-08j,  2.35585258e-17-1.15553931e-06j,
        3.12280382e-17-6.74868911e-07j,  1.77275020e-17-5.34474218e-07j,
        2.58866963e-17-4.62881496e-07j,  1.20478229e-17-4.20551012e-07j,
        2.73484232e-17-3.98470568e-07j,  8.69167792e-18-3.93414025e-07j,
        1.66763338e-17-4.18409935e-07j,  1.45401381e-17-2.13961678e-07j,
        1.58351328e-17-1.99662411e-07j,  2.03706871e-17-1.54030922e-07j,
       -5.56292434e-18-2.23813604e-07j, -2.77742998e-18-2.28138669e-07j,
        2.29218318e-17-2.77265428e-03j,  2.40658157

In [15]:
bad_inds_2 = np.where(np.imag(pg_2) > 0)
bad_inds_2

(array([154, 155, 156, 159, 169, 170, 171, 180, 182, 184, 185, 186, 187,
        188, 189, 190, 191, 192, 194, 195, 196, 198, 199, 202, 203, 204,
        205, 206, 212, 214, 245, 247, 248, 249, 250, 253, 256, 257, 260,
        261, 267, 270, 272, 275, 294, 295, 303, 304, 306, 308, 309, 311,
        312, 314, 315, 317, 318, 323, 327, 333, 336, 339, 341, 342, 344,
        345, 347, 348, 349, 350, 351, 360, 363, 369, 372, 374, 377, 378,
        380, 381, 384, 390, 393, 394, 395, 401, 402, 406, 409, 411, 412,
        413, 414, 415, 416, 417, 419, 421, 422, 423, 424, 425, 427, 428,
        431, 434, 435, 436, 437, 438, 439, 442, 446, 448, 452, 454, 456,
        457, 458, 459, 460, 461, 464, 467, 473, 475, 476, 479, 481, 485,
        491, 494, 497, 498, 500, 506, 509]),)