This script compares the self-energy calculated with the Hilbert transform and the old way of calculating it.

In [337]:
import numpy as np

scratch_path = "/usr/scratch/bucaramanga/awinka/quatrex_results/testing/nokp/"
#iter_oldq = '_iter1_e-18.939393939393938_kp0_oldq.npy' From Rank 0 and last energy
#iter_hilb = '_iter1_e-18.939393939393938_kp0_hilb.npy'
iter_oldq = '_iter1_e-4.12512218963832_kp0_oldq.npy'
iter_hilb = '_iter1_e-4.12512218963832_kp0_hilb.npy'
sl_oldq = np.load(scratch_path + 'sl_h2g' + iter_oldq)
sg_oldq = np.load(scratch_path + 'sg_h2g' + iter_oldq)
sr_oldq = np.load(scratch_path + 'sr_h2g' + iter_oldq)
sl_hilb = np.load(scratch_path + 'sl_h2g' + iter_hilb)
sg_hilb = np.load(scratch_path + 'sg_h2g' + iter_hilb)
sr_hilb = np.load(scratch_path + 'sr_h2g' + iter_hilb)

In [264]:
sg_only_fock = sg_hilb
sl_only_fock = sl_hilb
sr_only_fock = sr_hilb

In [253]:
sg_no_fock = sg_hilb
sr_no_fock = sr_hilb
sl_no_fock = sl_hilb

In [169]:
sg_hilb_old = sg_hilb
sl_hilb_old = sl_hilb
sr_hilb_old = sr_hilb

In [180]:
sg_semi_old = sg_hilb
sl_semi_old = sl_hilb
sr_semi_old = sr_hilb

In [192]:
sg_hilb_old2 = sg_hilb
sl_hilb_old2 = sl_hilb
sr_hilb_old2 = sr_hilb

In [206]:
spec1_oldq = sg_oldq-sl_oldq
spec2_oldq = sr_oldq-sr_oldq.T.conj()
spec1_hilb = sg_hilb-sl_hilb
spec2_hilb = sr_hilb-sr_hilb.T.conj()

In [222]:
spec2_hilb_old = sr_hilb_old-sr_hilb_old.T.conj()
spec1_hilb_old = sg_hilb_old-sl_hilb_old

In [166]:
np.allclose(np.real(spec1_oldq), np.real(spec2_oldq))

True

In [167]:
np.real(spec1_oldq).max()

7.687882773428151e-17

In [168]:
np.real(spec2_oldq).max()

4.726080637951213e-14

In [310]:
sr_oldq.T[200, 190:210].conj()

array([ 6.07569093e-03-1.17575692e-03j,  3.89219058e-02-5.05535720e-07j,
        1.24609892e-02-9.46283003e-05j,  4.90088073e-02+2.53024670e-03j,
       -1.19253316e-02-4.47316753e-03j,  0.00000000e+00-0.00000000e+00j,
        0.00000000e+00-0.00000000e+00j,  0.00000000e+00-0.00000000e+00j,
        3.15465666e-02+6.64025202e-04j, -1.89013422e-12-5.16868042e-14j,
       -2.32814279e-01+3.62646782e-03j, -1.17546902e-01+2.05454986e-04j,
       -6.04941833e-13-5.50015772e-17j,  1.98034833e-01-7.41175711e-05j,
        1.06134728e-01-3.55956570e-03j, -1.83768249e-13-2.86933488e-14j,
        8.95871064e-04-7.54018952e-04j, -1.05502103e-12-7.11602124e-14j,
       -1.45056659e-02+4.28216894e-03j, -1.11847054e-02+1.35738118e-04j])

In [263]:
spec2_oldq

array([[ 0.00000000e+00-5.39289147e-14j,  6.22798652e-16+3.31691316e-17j,
         5.55111512e-17+2.25097840e-15j, ...,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j],
       [-6.22798652e-16+3.31691316e-17j,  0.00000000e+00-4.68171485e-14j,
        -1.14076219e-16-6.25674085e-17j, ...,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j],
       [-5.55111512e-17+2.25097840e-15j,  1.14076219e-16-6.25674085e-17j,
         0.00000000e+00-5.12576337e-14j, ...,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j],
       ...,
       [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j, ...,
         0.00000000e+00-4.88423928e-14j,  5.16662810e-16+3.42307707e-17j,
        -2.91433544e-16-3.25226074e-16j],
       [ 0.00000000e+00+0.00000000e+00j,  0.

In [270]:
sr_hilb-sr_hilb.T.conj()

array([[ 0.00000000e+00-4.69387483e-08j,  7.18281155e-16+2.16501671e-17j,
         1.38777878e-17+1.87215379e-09j, ...,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j],
       [-7.18281155e-16+2.16501671e-17j,  0.00000000e+00-3.95855207e-08j,
        -1.76555822e-17-5.94342442e-17j, ...,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j],
       [-1.38777878e-17+1.87215379e-09j,  1.76555822e-17-5.94342442e-17j,
         0.00000000e+00-4.28972344e-08j, ...,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j],
       ...,
       [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j, ...,
         0.00000000e+00-4.43593937e-08j, -3.04141831e-16+4.10431350e-17j,
        -2.67147415e-16-3.62502016e-10j],
       [ 0.00000000e+00+0.00000000e+00j,  0.

In [317]:
sr_hilb[0, :10]-sr_hilb.T[0,:10].conj() #+sr_no_fock.T[200, 190:210].conj()

array([ 0.00000000e+00-1.43991973e-02j,  5.26084229e-12-4.01997100e-12j,
        2.77648737e-12-1.32804465e-03j, -1.13327958e-11+6.04047446e-03j,
       -1.05244893e-12+5.29393665e-13j,  3.59851038e-13-2.84452027e-04j,
       -5.55111512e-15+4.27703398e-03j,  2.11824600e-12-4.82571368e-13j,
        2.41487386e-12+1.66069180e-02j,  2.44585366e-12-8.83042494e-13j])

In [335]:
sr_oldq[0, :10]-sr_oldq.T[0,:10].conj()

array([ 0.00000000e+00-1.43991973e-02j,  0.00000000e+00-4.02675668e-12j,
        6.93889390e-18-1.32804465e-03j,  0.00000000e+00+6.04047441e-03j,
       -3.23117427e-27+5.29661230e-13j,  2.77555756e-17-2.84452027e-04j,
        0.00000000e+00+4.27703391e-03j,  0.00000000e+00-4.88276200e-13j,
        0.00000000e+00+1.66069180e-02j, -2.58493941e-26-8.91912257e-13j])

In [332]:
sg_hilb[0, :10]-sl_hilb[0, :10]

array([-1.81931342e-18-1.43991056e-02j,  5.26078019e-12-4.01973247e-12j,
        2.77643062e-12-1.32805042e-03j, -1.13333400e-11+6.04050306e-03j,
       -1.05249532e-12+5.29325450e-13j,  3.59832311e-13-2.84444051e-04j,
       -5.02877367e-15+4.27703952e-03j,  2.11810431e-12-4.81950091e-13j,
        2.41493983e-12+1.66069369e-02j,  2.44566721e-12-8.82772345e-13j])

In [336]:
sg_oldq[0, :10]-sl_oldq[0, :10]

array([-1.18459386e-17-1.43991056e-02j,  5.26229263e-12-4.02651326e-12j,
        2.90816675e-12-1.32805041e-03j,  7.86815589e-12+6.04050301e-03j,
       -1.05247973e-12+5.29593018e-13j,  3.59358058e-13-2.84444051e-04j,
        4.63470558e-12+4.27703944e-03j,  2.11835788e-12-4.87654241e-13j,
        2.39948507e-12+1.66069369e-02j,  2.44752308e-12-8.91641856e-13j])

In [312]:
sr_semi_old.T[200, 190:210].conj() +sr_hilb.T[200, 190:210].conj()

array([ 1.34174137e-02-1.17575231e-03j,  8.07389080e-02-5.05265342e-07j,
        2.90014464e-02-9.46304463e-05j,  1.01592285e-01+2.53024297e-03j,
       -2.01229199e-02-4.47316136e-03j,  0.00000000e+00-0.00000000e+00j,
        0.00000000e+00-0.00000000e+00j,  0.00000000e+00-0.00000000e+00j,
        7.77650880e-02+6.64021411e-04j,  5.82704239e-12+4.57597519e-13j,
       -6.53262730e-01+3.62651304e-03j, -2.36990129e-01+2.05462487e-04j,
       -1.50106689e-12+1.54355478e-13j,  3.97944200e-01-7.41164835e-05j,
        2.19901187e-01-3.55955975e-03j,  2.10857805e-12+5.34651932e-14j,
        4.81173372e-03-7.54023220e-04j, -2.32707783e-12+1.33034091e-13j,
       -2.93143020e-02+4.28216576e-03j, -2.29150926e-02+1.35736052e-04j])

In [303]:
sg_hilb.T.conj()[200, 196:204]

array([ 0.00000000e+00-0.00000000e+00j,  0.00000000e+00-0.00000000e+00j,
        1.39317709e-19+2.09681349e-18j, -1.82225488e-26-2.34265096e-26j,
       -9.69444619e-18+1.05934656e-16j, -1.60945011e-17-2.77117647e-17j,
       -3.28301183e-28+5.85554205e-28j,  2.62608919e-17+1.12566482e-17j])

In [301]:
sg_hilb[200, 196:204]

array([ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        6.00682227e-19-1.76435892e-18j,  2.20507182e-26+2.54530049e-26j,
       -9.69444619e-18-1.05934656e-16j,  1.55398456e-17+2.65025688e-17j,
        1.87555244e-28-4.23683733e-28j, -2.57861138e-17-7.38871274e-18j])

In [287]:
sr_hilb.T[200, 190:210]

array([ 7.35676384e-03-3.45503178e-10j,  4.16205058e-02-8.56949332e-10j,
        1.63425116e-02+7.09057551e-10j,  5.24194918e-02-1.15290853e-09j,
       -8.02056000e-03+1.86099597e-10j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        4.76595058e-02+9.32501464e-10j, -6.94769616e-12-3.97350796e-12j,
       -4.60234748e-01-2.14485920e-08j, -1.19570132e-01+9.93891785e-10j,
       -6.80890240e-13-4.59697202e-14j,  2.00646481e-01-2.55905650e-09j,
        1.13973746e-01+1.47268404e-09j, -2.62389703e-13-4.10410307e-13j,
        4.17260820e-03-4.81167259e-10j,  2.71885171e-14+6.39713853e-13j,
       -1.56913992e-02+1.76139472e-09j, -1.17480304e-02+3.21436445e-11j])

In [280]:
sr_hilb.T[200, 190:210] #-sr_hilb_old.T[200, 190:210]

array([ 7.40644632e-03+3.44511287e-10j,  4.20148178e-02+8.57730455e-10j,
        1.67382410e-02-7.09019927e-10j,  5.26694527e-02+1.15453459e-09j,
       -8.20147494e-03-1.87429475e-10j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        4.46982910e-02-9.34580418e-10j,  5.84854345e-14-5.32373101e-13j,
       -3.80814287e-01+2.14485920e-08j, -1.19314661e-01-9.93102453e-10j,
       -6.48421104e-13-7.40740745e-14j,  1.99171420e-01+2.55824263e-09j,
        1.13583035e-01-1.47277806e-09j, -1.27468703e-13+2.79858434e-14j,
        3.75202680e-03+4.81177652e-10j, -1.02596763e-12+2.18354776e-13j,
       -1.41677671e-02-1.76143579e-09j, -1.17306308e-02-3.21717931e-11j])

In [249]:
sg_hilb_old[200, 190:210] - sl_hilb_old[200, 190:210]

array([ 5.67943424e-18+1.89317756e-17j, -2.41469618e-18+1.18299990e-16j,
       -4.84314929e-18+2.62886068e-17j, -7.97642760e-18+1.21774851e-16j,
       -5.30521286e-18-1.68986280e-17j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        2.57915659e-18+5.73538378e-17j,  3.46328951e-26+3.65748647e-26j,
       -2.61454267e-17-6.86694010e-16j,  8.36216369e-18-3.72326143e-17j,
        3.93425523e-27+6.59203933e-29j,  3.21048159e-18+1.52507495e-16j,
       -7.68886529e-18+1.04093862e-16j,  4.88933843e-26+4.22844607e-26j,
       -1.18432014e-17+1.31210309e-17j,  2.53082473e-26+2.77674242e-26j,
        7.63865632e-18-8.79225799e-17j,  5.82642583e-18+6.63195254e-19j])

In [243]:
spec2_oldq[200, 190:210]

array([ 7.89299182e-17+1.15582033e-17j, -1.11022302e-16+2.74613274e-17j,
        2.08166817e-17+6.90075407e-18j,  9.71445147e-17+1.31082704e-17j,
        6.93889390e-18-7.64673889e-19j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        3.40005801e-16+4.94340578e-17j, -2.08957685e-17-2.71846424e-26j,
        0.00000000e+00-4.76650251e-16j,  6.38378239e-16+1.57287063e-17j,
        3.81698706e-16-1.15951826e-27j, -1.38777878e-16+8.65510136e-17j,
        1.38777878e-16+6.17078016e-18j, -3.31853755e-16-5.61764630e-27j,
       -1.10154941e-16+1.42035983e-17j, -2.81804073e-16+4.62572578e-27j,
       -1.73472348e-16-2.38972502e-17j, -2.70616862e-16+9.08680820e-18j])