In [100]:
import numpy as np

scratch_path = '/usr/scratch/bucaramanga/awinka/quatrex_results/self_energy_data/'

sg_new = np.load(scratch_path + 'sg_gw2s_new.npy')
sl_new = np.load(scratch_path + 'sl_gw2s_new.npy')
sr_new = np.load(scratch_path + 'sr_gw2s_new.npy')
sg_old = np.load(scratch_path + 'sg_gw2s_old.npy')
sl_old = np.load(scratch_path + 'sl_gw2s_old.npy')
sr_old = np.load(scratch_path + 'sr_gw2s_old.npy')
sl_hilb = np.load(scratch_path + 'sl_gw2s_hilb.npy')
sg_hilb = np.load(scratch_path + 'sg_gw2s_hilb.npy')
sr_hilb = np.load(scratch_path + 'sr_gw2s_hilb.npy')

In [109]:
sg_new.shape

(728, 1536)

In [242]:
orb = 13
print(sr_hilb[orb, 532:538])
print(sr_old[orb, 532:538])
print(np.allclose(sr_hilb, sr_old))
np.where(abs(np.imag(sr_hilb - sr_old)) > 1e-2)[1][144:160]

[-0.02212626-0.03203481j -0.02174166-0.03204582j -0.02233419-0.03190415j
 -0.02227093-0.03440017j -0.02095889-0.03535354j -0.02004294-0.03590207j]
[-0.01351289-0.03308488j -0.01326132-0.033157j   -0.01329667-0.03304861j
 -0.01310377-0.03551485j -0.01247907-0.03642716j -0.0119616 -0.03689875j]
False


array([   0,  432,  511, 1023, 1024, 1456,  176,  411,  414,  418,  419,
        432,  511,  923, 1024, 1196])

In [56]:
orb = 0
print(sr_new[orb,10:20])
print(sr_old[orb,10:20])
np.allclose(sg_hilb, sg_old)

[-0.1936491 -0.13854626j -0.19403826-0.13878413j -0.19442889-0.13902283j
 -0.19482099-0.13926238j -0.19521457-0.13950277j -0.19560965-0.13974402j
 -0.19600622-0.13998612j -0.1964043 -0.14022908j -0.1968039 -0.14047291j
 -0.19720503-0.14071761j]
[-0.20340305-0.60219118j -0.1915528 -0.60117822j -0.18007739-0.59990293j
 -0.16955397-0.59378404j -0.16037942-0.58844892j -0.15323548-0.57950155j
 -0.14575263-0.58293036j -0.13736318-0.57543906j -0.13105743-0.56730294j
 -0.12525248-0.56427611j]


True

In [33]:
orb = 20
print(sr_new[orb, 775:785])
print(sr_old[orb, 775:785]*3.535)

[-0.0013986 -2.94520670e-05j -0.00140213-3.46637826e-05j
 -0.00140664-3.97133487e-05j -0.00141273-4.49402219e-05j
 -0.00142117-5.08260407e-05j -0.0014331 -5.81360425e-05j
 -0.00145051-6.83418470e-05j -0.00147708-8.47850812e-05j
 -0.00151997-1.16132708e-04j -0.0016049 -1.88635066e-04j]
[-1.11247262e-03-0.00317779j -9.65190603e-04-0.00321004j
 -8.13307965e-04-0.00321617j -6.53880602e-04-0.00319202j
 -4.84519413e-04-0.00312634j -3.04949190e-04-0.00299935j
 -1.19231962e-04-0.0027826j   6.49818961e-05-0.00244843j
  2.73533705e-04-0.00200387j  1.24379058e-04-0.0002413j ]


In [244]:
import numpy as np

scratch_path = '/usr/scratch/bucaramanga/awinka/quatrex_results/self_energy_data/'

sg = np.load(scratch_path + 'sg_h2g_iter1_e-10.0_kp0.npy')
sl = np.load(scratch_path + 'sl_h2g_iter1_e-10.0_kp0.npy')
sr = np.load(scratch_path + 'sr_h2g_iter1_e-10.0_kp0.npy')

In [249]:
spec1 = sg-sl
spec2 = sr-sr.T.conj()

In [275]:
print(spec1[0:3, 0:3]/2)
print(spec2[0:3, 0:3])
np.allclose(np.imag(spec1), np.imag(spec2)*2, rtol=1e-2)

[[ 5.96196279e-17-0.36505139j  0.00000000e+00+0.j
   0.00000000e+00+0.j        ]
 [ 0.00000000e+00+0.j          7.11767650e-17-0.57366415j
   0.00000000e+00+0.j        ]
 [ 0.00000000e+00+0.j          0.00000000e+00+0.j
  -6.67057094e-17-1.01334379j]]
[[0.-0.36505032j 0.+0.j         0.+0.j        ]
 [0.+0.j         0.-0.57366599j 0.+0.j        ]
 [0.+0.j         0.+0.j         0.-1.0133429j ]]


True

In [38]:
import numpy as np

# Convolution testing
nzeros1 = 8
nzeros2 = 0
x1 = np.concatenate((np.zeros(nzeros1), np.array([1, 2, 3, 4, 5, 6, 7 , 8]), np.zeros(nzeros2)))
x2 = x1[::-1]  #np.array([1, 2, 3, 4, 5])
np.convolve(x1, x2)

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   8.,  23.,  44.,
        70., 100., 133., 168., 204., 168., 133., 100.,  70.,  44.,  23.,
         8.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [39]:
x1_t = np.fft.fft(x1, n=2*len(x1)-1)
x2_t = np.fft.fft(x2, n=2*len(x2)-1)
np.real(np.round(np.fft.ifft(x1_t*x2_t)))

array([  0.,   0.,   0.,  -0.,  -0.,  -0.,  -0.,  -0.,   8.,  23.,  44.,
        70., 100., 133., 168., 204., 168., 133., 100.,  70.,  44.,  23.,
         8.,  -0.,  -0.,  -0.,  -0.,  -0.,   0.,   0.,   0.])

In [34]:
print(np.linspace(0, 7, 8, endpoint=True))
print(np.linspace(0, 7+7, 15, endpoint=True))

[0. 1. 2. 3. 4. 5. 6. 7.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
