In [3]:
import numpy as np

PATH = '/usr/scratch/bucaramanga/awinka/quatrex_results/testing/'

wg = np.load(PATH + 'wg_diag.npy')
wr = np.load(PATH + 'wr_diag.npy')
wl = np.load(PATH + 'wl_diag.npy')

In [6]:
spec1 = wg - wl
spec2 = wr - wr.transpose((0,1,3,2)).conj()

In [13]:
np.where(np.abs(spec1-spec2)/np.abs(spec1) > 1e-4)

/tmp/ipykernel_1682359/493650026.py:1: RuntimeWarning: invalid value encountered in divide
  np.where(np.abs(spec1-spec2)/np.abs(spec1) > 1e-4)


(array([ 1,  1,  1, ..., 46, 46, 46]),
 array([0, 0, 0, ..., 5, 5, 5]),
 array([  0,   0,   0, ..., 113, 118, 119]),
 array([11, 12, 13, ..., 31, 22, 25]))

In [14]:
spec1[1, 0, 0, 11:]

array([ 5.55193242e-08-9.02110180e-05j,  5.54373812e-08-8.97960967e-05j,
        5.54111204e-08-8.98233340e-05j,  6.79774154e-08-1.17748608e-04j,
        6.93233561e-08-1.18027706e-04j,  6.93231546e-08-1.18027706e-04j,
        6.66891962e-08-1.13855475e-04j,  6.62669022e-08-1.14532707e-04j,
        5.48074217e-08-8.90388014e-05j,  5.47423482e-08-8.86558802e-05j,
        5.46855473e-08-8.86878552e-05j,  8.28876571e-08-6.96719974e-05j,
        8.30678120e-08-6.92032681e-05j,  8.26226923e-08-6.93532372e-05j,
        1.07562213e-07-8.97237571e-05j,  1.05787323e-07-9.02523355e-05j,
        1.05786951e-07-9.02523355e-05j,  9.88020952e-08-8.75198294e-05j,
        1.00093559e-07-8.70903164e-05j,  8.13023642e-08-6.87402412e-05j,
        8.14336730e-08-6.83047439e-05j,  8.10675337e-08-6.84485829e-05j,
        7.56256853e-08-4.22873260e-05j,  7.55909030e-08-4.21363523e-05j,
        7.55020322e-08-4.21468161e-05j,  9.78386642e-08-5.64962889e-05j,
        9.86441049e-08-5.66043875e-05j,  9.86437834

In [15]:
spec2[1, 0, 0, 11:]

array([ 8.86490881e-12-9.02110182e-05j,  9.07629527e-12-8.97960969e-05j,
        9.07629527e-12-8.98233343e-05j,  9.75397541e-12-1.17748609e-04j,
        1.00026654e-11-1.18027706e-04j,  9.80149295e-12-1.18027706e-04j,
        9.20996612e-12-1.13855475e-04j,  9.49729184e-12-1.14532708e-04j,
        8.90826167e-12-8.90388016e-05j,  9.12306451e-12-8.86558804e-05j,
        9.11675093e-12-8.86878554e-05j,  1.15067955e-11-6.96719975e-05j,
        1.16358034e-11-6.92032682e-05j,  1.17132970e-11-6.93532373e-05j,
        1.72408754e-11-8.97237571e-05j,  1.70574666e-11-9.02523356e-05j,
        1.66839875e-11-9.02523356e-05j,  1.59399161e-11-8.75198296e-05j,
        1.61286540e-11-8.70903165e-05j,  1.13733538e-11-6.87402413e-05j,
        1.15037779e-11-6.83047440e-05j,  1.16041948e-11-6.84485830e-05j,
        1.32441973e-11-4.22873259e-05j,  1.35278430e-11-4.21363522e-05j,
        1.34340224e-11-4.21468160e-05j,  1.66371196e-11-5.64962888e-05j,
        1.69413342e-11-5.66043874e-05j,  1.66193142