In [5]:
import numpy as np
from scipy.signal import convolve2d
shape = (4,4)

dim = len(shape)

size = np.prod(np.array(shape))

padding = ((0,0), (0,shape[1]))
#padding = ((0,shape[0]), (0,shape[1]))

x = np.arange(size).reshape(shape)
x_pad = np.pad(x, padding)

In [19]:
convolve2d(x,x)

array([[   0,    0,    1,    4,   10,   12,    9],
       [   0,    8,   26,   56,   68,   64,   42],
       [  16,   56,  123,  220,  222,  188,  115],
       [  64,  176,  340,  560,  520,  416,  244],
       [ 160,  368,  627,  940,  798,  596,  331],
       [ 192,  424,  698, 1016,  836,  608,  330],
       [ 144,  312,  505,  724,  586,  420,  225]])

In [67]:
np.convolve(x,x)

array([ 0,  0,  1,  4, 10, 12,  9])

In [14]:
x.size

16

In [20]:
x_fl = np.concatenate((x.ravel(), np.zeros(x.size)))# x_pad
pad_size = x_fl.size
conv_test1 = np.zeros(pad_size)

for i in range(pad_size):
    for j in range(pad_size):
        x_flattened = x_fl.ravel()
        conv_test1[i] += x_flattened[j]*x_flattened[i-j]
conv_test1.reshape(x_pad.shape).astype(np.int)

/tmp/ipykernel_3689038/2654393639.py:9: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  conv_test1.reshape(x_pad.shape).astype(np.int)


array([[   0,    0,    1,    4,   10,   20,   35,   56],
       [  84,  120,  165,  220,  286,  364,  455,  560],
       [ 680,  784,  871,  940,  990, 1020, 1029, 1016],
       [ 980,  920,  835,  724,  586,  420,  225,    0]])

In [10]:
x_2d = x_pad
conv_test2 = np.zeros(x_2d.shape)

for j2 in range(x_2d.shape[1]):
    for i1 in range(x_2d.shape[0]):
        for i2 in range(x_2d.shape[1]):
            for j1 in range(x_2d.shape[0]):
                conv_test2[i1, i2] += x_2d[j1, j2]*x_2d[i1-j1, i2-j2]
conv_test2.astype(np.int)

/tmp/ipykernel_3689038/843273668.py:9: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  conv_test2.astype(np.int)


array([[ 160,  368,  628,  944,  808,  608,  340,    0],
       [ 192,  432,  724, 1072,  904,  672,  372,    0],
       [ 160,  368,  628,  944,  808,  608,  340,    0],
       [  64,  176,  340,  560,  520,  416,  244,    0]])

In [31]:
conv_test3 = np.zeros(shape)

for j2 in range(shape[1]):
    for i1 in range(shape[0]):
        for i2 in range(shape[1]):
            for j1 in range(shape[0]):
                for i3 in range(shape[2]):
                    for j3 in range(shape[2]):
                        conv_test3[i1, i2, i3] += x[j1, j2, j3]*x[i1-j1, i2-j2, i3-j3]
conv_test3

array([[[1408., 1472., 1536., 1344.],
        [1664., 1728., 1792., 1600.],
        [1920., 1984., 2048., 1856.],
        [1152., 1216., 1280., 1088.]],

       [[2432., 2496., 2560., 2368.],
        [2688., 2752., 2816., 2624.],
        [2944., 3008., 3072., 2880.],
        [2176., 2240., 2304., 2112.]],

       [[3456., 3520., 3584., 3392.],
        [3712., 3776., 3840., 3648.],
        [3968., 4032., 4096., 3904.],
        [3200., 3264., 3328., 3136.]],

       [[ 384.,  448.,  512.,  320.],
        [ 640.,  704.,  768.,  576.],
        [ 896.,  960., 1024.,  832.],
        [ 128.,  192.,  256.,   64.]]])

In [16]:
size = 4
conv_test1 = np.zeros(size)

for i in range(size):
    for j in range(size):
        x_flattened = np.arange(size)
        conv_test1[i] = x_flattened[j]*x_flattened[i-j]
conv_test1

array([3., 6., 9., 0.])

In [25]:
import numpy as np

ki1 = 2
ki2 = 4

num_kpoints = np.array([5])

nkpts = np.prod(num_kpoints)

ind_mat = np.arange(nkpts).reshape(num_kpoints)

mi1 = np.array(np.where(ind_mat==ki1))
mi2 = np.array(np.where(ind_mat==ki2))

md = tuple(mi1-mi2)

print(ind_mat[md])
#ind_mat[0,-1,1]
print(md)
print(ind_mat[ind_mat==mi1])

[3]
(array([-2]),)


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed